### ISSUE TITLE
Cannot update records by entry ID

### ISSUE THREAD

**Issue by SKLn-Rad** [flamelink/flamelink#138]
Hey! Hopefully this is a quick one but I was directly to create a ticket here.  

I am currently having issues getting the project set up to run updates.
I can get and create the records fine, but when I try an update I get an exception in Firebase Functions.

Code:
```
/**
   * Updates the FCM token of the user.
   * @param {string} uid The user ID of the user to update the FCM token for.
   * @param {string} fcmToken The FCM token to update.
   * @return {Promise<any>} The user profile.
   */
  export async function updateProfileFcmToken(
    uid: string,
    fcmToken: string
  ): Promise<any> {
    const flamelinkApp = flamelink({
      firebaseApp: adminApp,
      dbType: "cf",
      precache: false,
      env: "production", // We use multiple Firebase projects, so this is always production.
    });
    
    functions.logger.info(`Updating FCM token for user: ${uid} to ${fcmToken}`);
    return await flamelinkApp.content.update({
      schemaKey: "users",
      entryId: uid,
      data: {
        fcmToken: fcmToken,
      },
    });
  }
```

Exception:
```
Unhandled error TypeError: Cannot read properties of undefined (reading 'FieldValue')
    at Object.<anonymous> (/workspace/node_modules/@flamelink/sdk-content-cf/dist/cjs/index.js:2397:95)
    at step (/workspace/node_modules/@flamelink/sdk-content-cf/dist/cjs/index.js:81:23)
    at Object.next (/workspace/node_modules/@flamelink/sdk-content-cf/dist/cjs/index.js:62:53)
    at fulfilled (/workspace/node_modules/@flamelink/sdk-content-cf/dist/cjs/index.js:52:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Any help would be massively appreciated!

**Comment by SKLn-Rad** [comment]
For debugging, here are my dependencies.

```
"dependencies": {
    "cross-fetch": "^3.1.5",
    "firebase-admin": "^11.4.0",
    "firebase-functions": "^4.2.1",
    "flamelink": "^1.0.0-rc.2",
    "stream-chat": "^8.4.1"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.4",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^4.5.4"
  },
```
